# Generated by Django 3.1.7 on 2021-03-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=10)),
                ('descuento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('medio_pago', models.CharField(max_length=60)),
                ('entrega', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
    ]
